<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Client area notification</title>
	<style type='text/css'>
		<!--
		body {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			color: #000000;
		}
		p {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			line-height: 1.8em;
		}
		a, a:visited, a:active {
			text-decoration: underline;
			color: #1b5cce;
		}

		a:hover {
			text-decoration: none;
			color: #1b5cce;
		}
		-->
	</style>
</head>
<body>

<br />

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="100%" align="center">

			<table border="0" cellpadding="0" cellspacing="0" width="680">
				<tr>
					<td width="680" align="left">

						<h2>Details of domain contacts of [domain-&gt;Domain].[domain-&gt;Tld] have been edited</h2>

						<p style="line-height: 1.8em;">
							On <?php echo date('d-m-Y').' at '.date('H:i'); ?> an adjustment to the domain contacts of domain name <a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">[domain-&gt;Domain].[domain-&gt;Tld]</a> has been requested.
						</p>
					</td>
				</tr>
				<tr>
					<td width="680" align="left">

						<br />

						<h2>What do I need to do to process the adjustments?</h2>
						<?php if($domainChanged->ClientareaProfileObject->Rights['CLIENTAREA_DOMAIN_WHOIS_CHANGE'] == 'approve'){ ?>
							<p style="line-height: 1.8em;">You can approve, adjust or decline the request for adjustments via HostFact. Clicking on the link below, will directly take you to the page of the domain name.</p>
						<?php }else{ ?>
							<p style="line-height: 1.8em;">You don't have to do anything, because your settings state that adjustments of domain contacts details may be processed directly. The adjustments have already been processed. This email is only a notification and can be used to check whether the new details are correct.</p>
						<?php } ?>

						<br />

						<p>
							<a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">Go to the domain name in HostFact</a>
						</p>

					</td>
				</tr>

				<tr>
					<td width="680" align="center">

						<br /><br />

						<font style="color:#666666;font-size:0.8em">This is an automatically generated email from your HostFact</font>

					</td>
				</tr>
			</table>

		</td>
	</tr>
</table>

<br /><br />

</body>
</html>