<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Client area notification</title>
	<style type='text/css'>
		<!--
		body {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			color: #000000;
		}
		p {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			line-height: 1.8em;
		}
		a, a:visited, a:active {
			text-decoration: underline;
			color: #1b5cce;
		}

		a:hover {
			text-decoration: none;
			color: #1b5cce;
		}

		table.dns td {
			vertical-align: text-top;
		}

		table.dns td a {
			text-decoration: inherit;
			color: inherit;
		}

		tr.added td, td.added {
			background-color: #dff0d8;
		}

		tr.removed td, td.removed {
			background-color: #f2dede;
			text-decoration: line-through;
		}

		tr.changed td, td.changed {
			background-color: #fffbd4;
		}
		-->
	</style>
</head>
<body>

<br />

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="100%" align="center">

			<table border="0" cellpadding="0" cellspacing="0" width="680">
				<tr>
					<td width="680" align="left">

						<h2>DNS records of [domain-&gt;Domain].[domain-&gt;Tld] have been edited</h2>

						<p style="line-height: 1.8em;">
							On <?php echo date('d-m-Y').' at '.date('H:i'); ?> an adjustment to the DNS records of domain name <a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">[domain-&gt;Domain].[domain-&gt;Tld]</a> has been requested.
						</p>

						<?php if(!empty($recordTableContent)){ ?>
							<br />
							<hr />
							<table class="dns" border="0" cellpadding="5" cellspacing="0" width="100%">
								<tr>
									<th align="left" width="150">Name</th>
									<th align="left" width="80">Type</th>
									<th align="left" width="200">Value</th>
									<th align="left" width="50">TTL</th>
								</tr>
								<?php
								foreach($recordTableContent AS $table_row)
								{
									?>
									<tr <?php if($table_row['class'] != ''){ echo 'class="' . $table_row['class'] . '"'; } ?>>
										<?php
										foreach($table_row['columns'] AS $value)
										{
											echo '<td>' . $value . '</td>';
										}
										?>
									</tr>
									<?php
								}
								?>
							</table>
							<hr />
							<table>
								<tr>
									<td width="20" class="added"></td>
									<td width="160">&nbsp;New record</td>
									<td width="20" class="changed"></td>
									<td width="160">&nbsp;Changed record</td>
									<td width="20" class="removed"></td>
									<td width="160">&nbsp;Deleted record</td>
								</tr>
							</table>
						<?php } ?>
					</td>
				</tr>
				<tr>
					<td width="680" align="left">

						<br />

						<h2>What do I need to do to process the adjustments?</h2>
						<?php if($domainChanged->ClientareaProfileObject->Rights['CLIENTAREA_DOMAIN_DNSZONE_CHANGE'] == 'approve'){ ?>
							<p style="line-height: 1.8em;">You can approve, adjust or decline the request for adjustments via HostFact. Clicking on the link below, will directly take you to the page of the domain name.</p>
						<?php }else{ ?>
							<p style="line-height: 1.8em;">You don't have to do anything, because your settings state that adjustments of DNS records may be processed directly. The adjustments have already been processed. This email is only a notification and can be used to check whether the new details are correct.</p>
						<?php } ?>

						<br />

						<p>
							<a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">Go to the domain name in HostFact</a>
						</p>

					</td>
				</tr>

				<tr>
					<td width="680" align="center">

						<br /><br />

						<font style="color:#666666;font-size:0.8em">This is an automatically generated email from your HostFact</font>

					</td>
				</tr>
			</table>

		</td>
	</tr>
</table>

<br /><br />

</body>
</html>