<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Client area notification</title>
	<style type='text/css'>
		<!--
		body {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			color: #000000;
		}
		p {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			line-height: 1.8em;
		}
		a, a:visited, a:active {
			text-decoration: underline;
			color: #1b5cce;
		}

		a:hover {
			text-decoration: none;
			color: #1b5cce;
		}
		-->
	</style>
</head>
<body>

<br />

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="100%" align="center">

			<table border="0" cellpadding="0" cellspacing="0" width="680">
				<tr>
					<td width="680" align="left">

						<h2>Name servers from [domain-&gt;Domain].[domain-&gt;Tld] are edited</h2>

						<p style="line-height: 1.8em;">
							On <?php echo date('d-m-Y').' at '.date('H:i'); ?> an change has been requested for the name servers of domain name  <a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">[domain-&gt;Domain].[domain-&gt;Tld]</a>.
						</p>
					</td>
				</tr>
				<tr>
					<td width="680" align="center">
						<br />
						<hr />
						<table border="0" cellpadding="5" cellspacing="0" width="100%">
							<tr>
								<td></td>
								<td><strong>Current details</strong></td>
								<td><strong>New details</strong></td>
							</tr>
							<tr>
								<td>Nameserver 1</td>
								<td><?php echo $domain->DNS1; ?></td>
								<td><?php echo $domainChanged->DNS1; ?></td>
							</tr>
							<tr>
								<td>Nameserver 2</td>
								<td><?php echo $domain->DNS2; ?></td>
								<td><?php echo $domainChanged->DNS2; ?></td>
							</tr>
							<tr>
								<td>Nameserver 3</td>
								<td><?php echo $domain->DNS3; ?></td>
								<td><?php echo $domainChanged->DNS3; ?></td>
							</tr>

						</table>

						<hr />
					</td>

				</tr>
				<tr>
					<td width="680" align="left">

						<br />

						<h2>What do I need to do to process the adjustments?</h2>
						<?php if($domainChanged->ClientareaProfileObject->Rights['CLIENTAREA_DOMAIN_NAMESERVER_CHANGE'] == 'approve'){ ?>
							<p style="line-height: 1.8em;">You can approve, adjust or decline the request for adjustments via HostFact. Clicking on the link below will directly take you to the page of the domain name.</p>
						<?php }else{ ?>
							<p style="line-height: 1.8em;">You don't have to do anything, because your settings state that all changes of name servers may be processed automatically. You can use this notification to check whether the new details are correct.</p>
						<?php } ?>

						<br />

						<p>
							<a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">Go to the domain name in HostFact</a>
						</p>

					</td>
				</tr>

				<tr>
					<td width="680" align="center">

						<br /><br />

						<font style="color:#666666;font-size:0.8em">This is an automatically generated email from your HostFact</font>

					</td>
				</tr>
			</table>

		</td>
	</tr>
</table>

<br /><br />

</body>
</html>