<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Client area notification</title>
	<style type='text/css'>
		<!--
		body {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			color: #000000;
		}
		p {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			line-height: 1.8em;
		}
		a, a:visited, a:active {
			text-decoration: underline;
			color: #1b5cce;
		}

		a:hover {
			text-decoration: none;
			color: #1b5cce;
		}
		-->
	</style>
</head>
<body>

<br />

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="100%" align="center">

			<table border="0" cellpadding="0" cellspacing="0" width="680">
				<tr>
					<td width="680" align="left">

						<h2>Estimate [pricequote-&gt;PriceQuoteCode] has been accepted</h2>

						<p style="line-height: 1.8em;">
							On <?php echo date('d-m-Y').' at '.date('H:i'); ?> the estimate <a href="<?php echo BACKOFFICE_URL ?>pricequotes.php?page=show&id=[pricequote-&gt;Identifier]">[pricequote-&gt;PriceQuoteCode]</a> ([pricequote-&gt;AmountExcl]) has been accepted.<br />
							<br />
							<strong>Klantgegevens [debtor-&gt;DebtorCode]:</strong><br />
							<?php if($debtor->CompanyName != ''){ ?>[debtor-&gt;CompanyName]<br/><?php } ?>
							[debtor-&gt;Initials] [debtor-&gt;SurName]<br/>
							[debtor-&gt;Address]<br/>
							[debtor-&gt;ZipCode] [debtor-&gt;City]<br/>
							[debtor-&gt;CountryLong]<br/>
							<br/>
							<?php if($debtor->PhoneNumber != ''){ ?>T: [debtor-&gt;PhoneNumber]<br/><?php } ?>
							<?php if($debtor->EmailAddress != ''){ ?>E: <a href="mailto:[debtor-&gt;EmailAddress]">[debtor-&gt;EmailAddress]</a><br /><?php } ?>

							<?php if($pricequote->Reason){ ?>
								<br />
								<strong>Reason:</strong><br />
								<?php echo nl2br($pricequote->Reason); ?><br />
							<?php } ?>
						</p>

						<h2>How can I create an invoice?</h2>

						<p style="line-height: 1.8em;">You can create an invoice via HostFact with a simple mouse click. This can be done now, but can also be done later.</p>

						<br />

						<p>
							<a href="<?php echo BACKOFFICE_URL ?>pricequotes.php?page=show&id=[pricequote-&gt;Identifier]">Go to the estimate in HostFact</a>
						</p>

					</td>
				</tr>

				<tr>
					<td width="680" align="center">

						<br /><br />

						<font style="color:#666666;font-size:0.8em">This is an automatically generated email from your HostFact</font>

					</td>
				</tr>
			</table>

		</td>
	</tr>
</table>

<br /><br />

</body>
</html>