<div class="domain_table">
	<table class="cart" cellpadding="0" cellspacing="0">
		<tr>
			<th><?php echo __('domaintable domain'); ?></th>
			<th width="90"><?php echo __('domaintable result'); ?></th>
			
			<th width="100" class="textright"><?php echo __('domaintable price'); ?></th>
			<th width="5">&nbsp;</th>
			<th width="90"><?php echo __('domaintable period'); ?></th>
		</tr>
		<?php
		foreach($domains as $tmp_domain)
		{
			?>
			<tr>
				<td>
					<a class="ico-del" onclick="removeDomainFromCart('<?php echo $tmp_domain['Domain']; ?>');"><img src="<?php echo ORDERFORM_URL; ?>images/delete.png" alt="X" /></a>
					<?php echo $tmp_domain['Domain']; ?>
					<?php
					// If domain needs EPP code, ask for code 
					if($tmp_domain['Availability'] == "unavailable" && isset($tmp_domain['AskForAuthKey']) && $tmp_domain['AskForAuthKey'] == true)
					{ 
						?>
						<br />
						<div class="auth_key"><?php echo __('authkey'); ?>: <input type="text" name="AuthKey[<?php echo $tmp_domain['Domain']; ?>]" value="<?php if(isset($tmp_domain['AuthKey'])){ echo $tmp_domain['AuthKey']; } ?>"/></div>
						<?php 
					} 
					?>		
				</td>
				<td><?php if($tmp_domain['Availability']){ echo ($tmp_domain['Availability'] == 'available') ? __('domain status available') : __('domain status unavailable'); }else{ echo __('domain status error'); } ?></td>
				
				<td class="textright"><?php echo w_money((SHOW_VAT_INCLUDED) ? $tmp_domain['PriceIncl'] : $tmp_domain['PriceExcl']); ?></td>
				<td>&nbsp;</td>
				<td><?php echo w_period(1, $tmp_domain['Periodic'], 'per'); ?></td>
			</tr>
			<?php
		}
		?>
	</table>
	
	<p><a href="?step=start&amp;cart=<?php echo ORDERFORM_ID; ?>"><?php echo __('add another domain'); ?></a></p>
</div>