<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
	<a href="#" data-toggle="modal" data-target="#deactivate-two-factor" data-backdrop="static">
		<?php echo __('two step authentication - deactivate link'); ?>
	</a>

	<!-- Modal -->
	<div class="modal fade" id="deactivate-two-factor" tabindex="-1" role="dialog" aria-labelledby="deactivate-two-factor" aria-hidden="true">
		<div class="modal-dialog" role="form">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title">
						<?php echo __('two step authentication deactivate - title'); ?>
					</h4>
				</div>

				<?php
				if (isset($message) && isset($_POST['Password']))
				{
					echo $message;
					unset($message);
				}
				?>

				<form id="form-deactivate-two-factor" class="" method="post" action="<?php echo __SITE_URL . '/' . __('debtor', 'url') . '/' . __('twoFactorDeactivate', 'url'); ?>">
					<div class="modal-body">
						<?php echo __('two step authentication deactivate - text'); ?>
						<br /><br />

						<div class="form-group row">
							<label class="col-sm-4 form-control-label"><?php echo __('password'); ?></label>
							<div class="col-sm-7">
								<input class="form-control" type="password" name="Password" value="" autocomplete="off">
							</div>
						</div>


					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary pull-left" data-dismiss="modal"><?php echo __('cancel'); ?></button>
						<button type="submit" class="btn btn-danger"><?php echo __('confirm'); ?></button>
					</div>

				</form>

			</div>
		</div>
	</div>
