<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<div class="modal fade" id="decline-pricequote" tabindex="-1" role="dialog" aria-labelledby="declineModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="form">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="declineModalLabel">
					<?php echo __('modal title decline pricequote'); ?>
				</h4>
			</div>

			<?php
			if (isset($message))
			{
				echo $message;
				unset($message);
			}
			?>
			<form id="form-decline-pricequote" class="" method="post" action="<?php echo __SITE_URL; ?>/<?php echo __('pricequote', 'url'); ?>/<?php echo __('decline', 'url'); ?>/<?php echo normalize($pricequote_object->id); ?>">

				<div class="modal-body p-b-0">

					<dl class="dl-horizontal">
						<dt class="col-sm-4"><?php echo __('pricequote code'); ?></dt>
						<dd class="col-sm-8"><?php echo normalize($pricequote_object->PriceQuoteCode); ?></dd>

						<dt class="col-sm-4"><?php echo __('pricequote date'); ?></dt>
						<dd class="col-sm-8"><?php echo rewrite_date_db2site($pricequote_object->Date); ?></dd>

					</dl>


					<div class="form-group row m-t-2">
						<label class="form-control-label col-sm-4"><?php echo __('comment'); ?></label>
						<div class="col-sm-7">
							<textarea class="form-control" name="Comment"><?php if(isset($pricequote_object->Reason)){ echo normalize($pricequote_object->Reason); } ?></textarea>
						</div>
					</div>

					<div class="form-group row">
						<label class="col-sm-4 form-control-label"><?php echo __('password'); ?></label>
						<div class="col-sm-7">
							<input class="form-control" type="password" name="Password" value="" autocomplete="off">
						</div>
					</div>

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary pull-left" data-dismiss="modal"><?php echo __('cancel'); ?></button>
					<button type="submit" class="btn btn-primary"><?php echo __('decline pricequote'); ?></button>
				</div>

			</form>

			<?php validate_input($pricequote_object->ErrorFields); ?>

		</div>
	</div>
</div>