<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<div class="col-xl-12 m-b-2">
	<div class="content-block p-a-2">

		<h1 class="font-large"><?php echo __('open tickets'); ?></h1>
		<?php

		$this->showElement('ticket.open');
		?>
	</div>
</div>

<?php
