<div class="o_form">

	<br />
	
	<h2><?php echo __('your payment is processed'); ?></h2>
	
	<?php if(isset($transaction_id) && $transaction_id){ ?>
	<p><?php echo __('transaction id'); ?>: <?php echo $transaction_id; ?></p>
	<?php } ?>
	
	<p>
		<?php echo __('we will process your order as soon as possible'); ?><br />
		<br />
		<?php echo COMPANY_NAME ?><br />
		<br />	
	</p>

</div>