<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<div class="col-lg-3 sidebar">

	<?php
	// call the sidebar widgets hook
	$sidebar_widgets = (!isset($sidebar_widgets)) ? array() : $sidebar_widgets;
	$this->generateSidebar($sidebar_widgets);
	?>

</div>
