<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<form class="form-password-reset m-t-1 text-xs-left" method="post" action="<?php echo __SITE_URL; ?>/<?php echo __('login', 'url'); ?>/<?php echo __('resetPassword', 'url'); ?>">

	<?php
	if (isset($message))
	{
		echo $message;
	}
	?>

	<h2><?php echo __('password reset title'); ?></h2>

	<p><?php echo __('password reset description'); ?></p>

	<!--[if IE 9]><label><?php echo __('new password'); ?></label><![endif]-->
	<input type="Password" class="form-control m-b-1" name="NewPassword" placeholder="<?php echo __('new password'); ?>" required="" autofocus="" autocomplete="off">

	<!--[if IE 9]><label><?php echo __('repeat new password'); ?></label><![endif]-->
	<input type="password" class="form-control" name="NewPasswordRepeat" placeholder="<?php echo __('repeat new password'); ?>" required="" autocomplete="off">

	<button class="btn btn-primary btn-block m-t-1" type="submit"><?php echo __('submit'); ?></button>
</form>