<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<form class="form-forgot-password m-t-1 m-b-2 text-xs-left" method="post" action="<?php echo __SITE_URL; ?>/<?php echo __('login', 'url'); ?>/<?php echo __('forgotPassword', 'url'); ?>">

	<?php
	if (isset($message))
	{
		echo $message;
	}
	?>

	<h2><?php echo __('password forgot title'); ?></h2>

	<p><?php echo __('password forgot description'); ?></p>

	<div class="form-group">
		<!--[if IE 9]><label><?php echo __('username'); ?></label><![endif]-->
		<input type="text" class="form-control m-b-1" name="Username" placeholder="<?php echo __('username'); ?>" required="" autofocus="" value="<?php if(isset($debtor->Username)){ echo normalize($debtor->Username); } ?>">
	</div>

	<div class="form-group">
		<!--[if IE 9]><label><?php echo __('emailaddress'); ?></label><![endif]-->
		<input type="email" class="form-control" name="EmailAddress" placeholder="<?php echo __('emailaddress'); ?>" required="" value="<?php if(isset($debtor->Username)){ echo normalize($debtor->EmailAddress); } ?>">
	</div>

	<button class="btn btn-primary btn-block m-t-1" type="submit"><?php echo __('submit'); ?></button>
</form>

<a href="<?php echo __SITE_URL . '/' . __('login', 'url'); ?>" class="text-muted back-to-login"><?php echo __('back to login page'); ?></a>

<?php validate_input($debtor->ErrorFields); ?>