<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<div class="row">
	<div class="col-xl-8 offset-xl-2">

		<div class="p-a-1 m-t-3">

			<h1><?php echo __('page not found title'); ?></h1>

			<p><?php echo __('page not found text'); ?></p>

		</div>
	</div>
</div>
