<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<div class="col-xl-9 col-lg-8">
	<div class="main-content p-a-2">

		<h1><?php echo __('open pricequotes'); ?></h1>

		<?php
			$this->showElement('pricequote.open');
		?>

	</div>
</div>


