<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<div class="col-xl-9 col-lg-8">
	<div class="main-content p-a-2">

		<?php
			if (isset($message))
			{
				echo $message;
			}

			$this->showElement('service.terminate');
		?>

		<h1><?php echo __('other service') . ' ' . normalize($service->Subscription['Description']); ?></h1>

		<?php
			show_termination_warning($service);

			$this->showElement('service.subscription');
		?>
	</div>
</div>