<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Notificatie via het klantenpaneel</title>
	<style type='text/css'>
		<!--
		body {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			color: #000000;
		}
		p {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			line-height: 1.8em;
		}
		a, a:visited, a:active {
			text-decoration: underline;
			color: #1b5cce;
		}

		a:hover {
			text-decoration: none;
			color: #1b5cce;
		}

		table.dns td {
			vertical-align: text-top;
		}

		table.dns td a {
			text-decoration: inherit;
			color: inherit;
		}

		tr.added td, td.added {
			background-color: #dff0d8;
		}

		tr.removed td, td.removed {
			background-color: #f2dede;
			text-decoration: line-through;
		}

		tr.changed td, td.changed {
			background-color: #fffbd4;
		}
		-->
	</style>
</head>
<body>

<br />

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="100%" align="center">

			<table border="0" cellpadding="0" cellspacing="0" width="680">
				<tr>
					<td width="680" align="left">

						<h2>DNS records van [domain-&gt;Domain].[domain-&gt;Tld] gewijzigd</h2>

						<p style="line-height: 1.8em;">
							Op <?php echo date('d-m-Y').' om '.date('H:i'); ?>  is er een wijziging aangevraagd voor de DNS records van domeinnaam  <a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">[domain-&gt;Domain].[domain-&gt;Tld]</a>.
						</p>

						<?php if(!empty($recordTableContent)){ ?>
							<br />
							<hr />
							<table class="dns" border="0" cellpadding="5" cellspacing="0" width="100%">
								<tr>
									<th align="left" width="150">Naam</th>
									<th align="left" width="80">Type</th>
									<th align="left" width="200">Waarde</th>
									<th align="left" width="50">TTL</th>
								</tr>
								<?php
									foreach($recordTableContent AS $table_row)
									{
										?>
										<tr <?php if($table_row['class'] != ''){ echo 'class="' . $table_row['class'] . '"'; } ?>>
											<?php
												foreach($table_row['columns'] AS $value)
												{
													echo '<td>' . $value . '</td>';
												}
											?>
										</tr>
										<?php
									}
								?>
							</table>
							<hr />
							<table>
								<tr>
									<td width="20" class="added"></td>
									<td width="160">&nbsp;Nieuw record</td>
									<td width="20" class="changed"></td>
									<td width="160">&nbsp;Aangepast record</td>
									<td width="20" class="removed"></td>
									<td width="160">&nbsp;Verwijderd record</td>
								</tr>
							</table>
						<?php } ?>
					</td>
				</tr>
				<tr>
					<td width="680" align="left">

						<br />

						<h2>Wat moet ik doen om de wijziging te verwerken?</h2>
						<?php if($domainChanged->ClientareaProfileObject->Rights['CLIENTAREA_DOMAIN_DNSZONE_CHANGE'] == 'approve'){ ?>
							<p style="line-height: 1.8em;">U kunt via HostFact het verzoek tot wijziging goedkeuren, aanpassen of weigeren. Door op onderstaande link te klikken, komt u direct op de pagina van de domeinnaam uit.</p>
						<?php }else{ ?>
							<p style="line-height: 1.8em;">U hoeft geen actie te ondernemen, omdat u heeft ingesteld dat wijzigingen van DNS records automatisch zullen worden verwerkt. U kunt deze notificatie gebruiken om te controleren of de wijzigingen correct zijn doorgevoerd.</p>
						<?php } ?>

						<p>
							<a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">Ga direct naar de domeinnaam in HostFact</a>
						</p>

					</td>
				</tr>

				<tr>
					<td width="680" align="center">

						<br /><br />

						<font style="color:#666666;font-size:0.8em">Dit is een automatisch verzonden e-mail vanuit uw HostFact</font>

					</td>
				</tr>
			</table>

		</td>
	</tr>
</table>

<br /><br />

</body>
</html>