<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Notificatie via het klantenpaneel</title>
	<style type='text/css'>
		<!--
		body {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			color: #000000;
		}
		p {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			line-height: 1.8em;
		}
		a, a:visited, a:active {
			text-decoration: underline;
			color: #1b5cce;
		}

		a:hover {
			text-decoration: none;
			color: #1b5cce;
		}
		-->
	</style>
</head>
<body>

<br />

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="100%" align="center">

			<table border="0" cellpadding="0" cellspacing="0" width="680">
				<tr>
					<td width="680" align="left">

						<h2>Facturatiegegevens van [debtor-&gt;DebtorCode] gewijzigd</h2>

						<p style="line-height: 1.8em;">
							Op <?php echo date('d-m-Y').' om '.date('H:i'); ?> heeft debiteur <a href="<?php echo BACKOFFICE_URL ?>debtors.php?page=edit&id=[debtor-&gt;Identifier]"><?php if($debtorOld->CompanyName != ''){ ?>[debtorOld-&gt;CompanyName]<?php }else{ ?>[debtorOld-&gt;Initials] [debtorOld-&gt;SurName]<?php } ?></a> facturatie gegevens gewijzigd via het klantenpaneel.
						</p>
					</td>
				</tr>
				<tr>
					<td width="680" align="center">
						<br />
						<hr />
						<table border="0" cellpadding="5" cellspacing="0" width="100%">
							<tr>
								<td></td>
								<td><strong>Huidige gegevens</strong></td>
								<td><strong>Gewijzigde gegevens</strong></td>
							</tr>
							<?php if($debtorOld->InvoiceCompanyName != '' || $debtorChanged->InvoiceCompanyName != ''){ ?>
								<tr>
									<td>Bedrijfsnaam</td>
									<td><?php echo ($debtorOld->InvoiceCompanyName != '') ? $debtorOld->InvoiceCompanyName : $debtorOld->CompanyName ; ?></td>
									<td><?php if($debtorChanged->InvoiceCompanyName != $debtorOld->InvoiceCompanyName){ echo ($debtorChanged->InvoiceCompanyName) ? $debtorChanged->InvoiceCompanyName : '-'; } ?></td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
							<?php } ?>
							<tr>
								<td>Contactpersoon</td>
								<td>
									<?php echo settings::getGenderTranslation($debtorOld->InvoiceSex) . ' '; ?>
									<?php echo (trim($debtorOld->InvoiceInitials.' '.$debtorOld->InvoiceSurName) != '') ? $debtorOld->InvoiceInitials.' '.$debtorOld->InvoiceSurName : $debtorOld->Initials.' '.$debtorOld->SurName ; ?>
								</td>
								<td>
									<?php
									if($debtorChanged->InvoiceInitials != $debtorOld->InvoiceInitials || $debtorOld->InvoiceSurName != $debtorChanged->InvoiceSurName || $debtorChanged->InvoiceSex != $debtorOld->InvoiceSex)
									{
										echo settings::getGenderTranslation($debtorChanged->InvoiceSex) . ' ';
										echo ($debtorChanged->InvoiceInitials || $debtorChanged->InvoiceSurName) ? $debtorChanged->InvoiceInitials.' '.$debtorChanged->InvoiceSurName : '-';
									}
									?>
								</td>
							</tr>
							<tr>
								<td>Adres</td>
								<td><?php echo $debtorOld->InvoiceAddress; if($debtorOld->InvoiceAddress2){ echo '<br />'.$debtorOld->InvoiceAddress2; } ?></td>
								<td><?php if($debtorChanged->InvoiceAddress != $debtorOld->InvoiceAddress || $debtorChanged->InvoiceAddress2 != $debtorOld->InvoiceAddress2){ echo ($debtorChanged->InvoiceAddress) ? $debtorChanged->InvoiceAddress : '-'; if($debtorChanged->InvoiceAddress2){ echo '<br />'.$debtorChanged->InvoiceAddress2; } } ?></td>
							</tr>
							<tr>
								<td>Postcode en plaats</td>
								<td><?php echo (trim($debtorOld->InvoiceZipCode.' '.$debtorOld->InvoiceCity) != '') ? $debtorOld->InvoiceZipCode.' '.$debtorOld->InvoiceCity : $debtorOld->ZipCode.' '.$debtorOld->City ; ?></td>
								<td><?php if($debtorChanged->InvoiceZipCode != $debtorOld->InvoiceZipCode || $debtorOld->InvoiceCity != $debtorChanged->InvoiceCity){ echo ($debtorChanged->InvoiceZipCode || $debtorChanged->InvoiceCity) ? $debtorChanged->InvoiceZipCode.' '.$debtorChanged->InvoiceCity : '-'; } ?></td>
							</tr>
							<?php if(IS_INTERNATIONAL){ ?>
								<tr>
									<td>Staat</td>
									<td><?php echo $debtorOld->InvoiceStateName; ?></td>
									<td><?php if($debtorChanged->InvoiceStateName != $debtorOld->InvoiceStateName){ echo ($debtorChanged->InvoiceStateName) ? $debtorChanged->InvoiceStateName : '-'; } ?></td>
								</tr>
							<?php } ?>
							<tr>
								<td>Land</td>
								<td><?php echo ($debtorOld->InvoiceCountryLong != '') ? $debtorOld->InvoiceCountryLong : $debtorOld->CountryLong ; ?></td>
								<td><?php if($debtorChanged->InvoiceCountryLong != $debtorOld->InvoiceCountryLong){ echo ($debtorChanged->InvoiceCountryLong) ? $debtorChanged->InvoiceCountryLong : '-'; } ?></td>
							</tr>

							<tr>
								<td>E-mailadres</td>
								<td><?php echo ($debtorOld->InvoiceEmailAddress != '') ? $debtorOld->InvoiceEmailAddress : $debtorOld->EmailAddress ; ?></td>
								<td><?php if($debtorChanged->InvoiceEmailAddress != $debtorOld->InvoiceEmailAddress){ echo ($debtorChanged->InvoiceEmailAddress) ? $debtorChanged->InvoiceEmailAddress : '-'; } ?></td>
							</tr>
						</table>

						<hr />
					</td>

				</tr>
				<tr>
					<td width="680" align="left">

						<br />

						<h2>Wat moet ik doen om de wijziging te verwerken?</h2>
						<?php if($debtorChanged->ClientareaProfileObject->Rights['CLIENTAREA_DEBTOR_DATA_CHANGE'] == 'approve'){ ?>
							<p style="line-height: 1.8em;">U kunt via HostFact het verzoek tot wijziging goedkeuren, aanpassen of weigeren. Door op onderstaande link te klikken, komt u direct op de pagina van de debiteur uit.</p>
						<?php }else{ ?>
							<p style="line-height: 1.8em;">U hoeft geen actie te ondernemen, omdat u heeft ingesteld dat wijzigingen van persoonlijke gegevens zijn toegestaan. De wijziging is daarom al doorgevoerd en deze e-mail geldt enkel ter notificatie.</p>
						<?php } ?>
						<hr />

						<p>
							<a href="<?php echo BACKOFFICE_URL ?>debtors.php?page=edit&id=[debtor-&gt;Identifier]">Ga direct naar de debiteur in HostFact</a>
						</p>

					</td>
				</tr>

				<tr>
					<td width="680" align="center">

						<br /><br />

						<font style="color:#666666;font-size:0.8em">Dit is een automatisch verzonden e-mail vanuit uw HostFact</font>

					</td>
				</tr>
			</table>

		</td>
	</tr>
</table>

<br /><br />

</body>
</html>