<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Notificatie via het klantenpaneel</title>
	<style type='text/css'>
		<!--
		body {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			color: #000000;
		}
		p {
			font-size:1em;
			font-family: 'Arial', 'Verdana', sans-serif;
			line-height: 1.8em;
		}
		a, a:visited, a:active {
			text-decoration: underline;
			color: #1b5cce;
		}

		a:hover {
			text-decoration: none;
			color: #1b5cce;
		}
		-->
	</style>
</head>
<body>

<br />

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="100%" align="center">

			<table border="0" cellpadding="0" cellspacing="0" width="680">
				<tr>
					<td width="680" align="left">

						<h2>WHOIS gegevens van [domain-&gt;Domain].[domain-&gt;Tld] gewijzigd</h2>

						<p style="line-height: 1.8em;">
							Op <?php echo date('d-m-Y').' om '.date('H:i'); ?>  is er een wijziging aangevraagd voor de WHOIS gegevens van domeinnaam  <a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">[domain-&gt;Domain].[domain-&gt;Tld]</a>.
						</p>
					</td>
				</tr>
				<tr>
					<td width="680" align="left">

						<br />

						<h2>Wat moet ik doen om de wijziging te verwerken?</h2>
						<?php if($domainChanged->ClientareaProfileObject->Rights['CLIENTAREA_DOMAIN_WHOIS_CHANGE'] == 'approve'){ ?>
							<p style="line-height: 1.8em;">U kunt via HostFact het verzoek tot wijziging goedkeuren, aanpassen of weigeren. Door op onderstaande link te klikken, komt u direct op de pagina van de domeinnaam uit.</p>
						<?php }else{ ?>
							<p style="line-height: 1.8em;">U hoeft geen actie te ondernemen, omdat u heeft ingesteld dat wijzigingen van WHOIS gegevens automatisch zullen worden verwerkt. U kunt deze notificatie gebruiken om te controleren of de wijzigingen correct zijn doorgevoerd.</p>
						<?php } ?>

						<p>
							<a href="<?php echo BACKOFFICE_URL ?>domains.php?page=show&id=[domain-&gt;Identifier]">Ga direct naar de domeinnaam in HostFact</a>
						</p>

					</td>
				</tr>

				<tr>
					<td width="680" align="center">

						<br /><br />

						<font style="color:#666666;font-size:0.8em">Dit is een automatisch verzonden e-mail vanuit uw HostFact</font>

					</td>
				</tr>
			</table>

		</td>
	</tr>
</table>

<br /><br />

</body>
</html>