<?php
/**
 * This is a core PHP file. For customization, create a file in the folder /custom/.
 * Files with the same filename in this folder will automatically be loaded instead of the current file
 */
?>
<div class="col-xl-3 col-lg-4 sidebar">
	<?php
	$sidebar_widgets[] = array('type'   => 'file',
							   'file'   => 'ticket.list');

	$this->generateSidebar($sidebar_widgets);
	?>
</div>
